require 'tilt'
require 'asciidoctor'

version = `git describe --tags HEAD`
if version == "" then version = "dev" end
date = `git log -1 --format=%ci | grep -o '^\\S*'`

desc 'Render the documentation'

task :clean do
    FileUtils.rm_rf('_build')
end

directory "_build"

file "_build/index.html" => "index.adoc" do |t|
    Asciidoctor.render_file t.prerequisites.first,
        :to_file => t.name,
        :in_place => true,
        :backend => 'html5',
        :mkdirs => true,
        :safe => :safe,
        :attributes => {
            'revnumber' => version,
            'revdate' => date,
        }
end

file "_build/01_krepios_guide.html" => "01_krepios_guide.adoc" do |t|
    Asciidoctor.render_file t.prerequisites.first,
        :to_file => t.name,
        :in_place => true,
        :backend => 'html5',
        :mkdirs => true,
        :safe => :safe,
        :attributes => {
            'revnumber' => version,
            'revdate' => date,
        }
end

file "_build/01_krepios_gm.html" => "01_krepios_gm.adoc" do |t|
    Asciidoctor.render_file t.prerequisites.first,
        :to_file => t.name,
        :in_place => true,
        :backend => 'html5',
        :mkdirs => true,
        :safe => :safe,
        :attributes => {
            'revnumber' => version,
            'revdate' => date,
        }
end

task :default => [:clean, "_build", "_build/index.html", "_build/01_krepios_guide.html", "_build/01_krepios_gm.html"] do
end